#ref https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually
# conda env create -f .devcontainer/conda_pyspark_environment.yml

name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - defaults
dependencies:
  - python=3.8
  - pyarrow==8.0.0
  - snowflake-snowpark-python
  - pandas
  - numpy
  - ipykernel
  - pip
  - pip:
    - snowflake-cli-labs
    - streamlit
    - jupyterlab
    - ijson
    - simplejson